version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: tenpo
      POSTGRES_DB: tenpo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app-generetor:
    build:
      context: otherApp/
    ports:
      - "8090:8090"

volumes:
  postgres-data: