version: '3.5'
services:

  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: tenpo
      POSTGRES_DB: tenpo
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data

  app-percentage:
    build:
      context: otherApp/
    ports:
      - "8090:8090"

  redis-db:
    image: redis:6-alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  tenpo:
    container_name: tenpo
    build:
      context: .
    depends_on:
      redis-db:
        condition: service_started
    environment:
      REDIS_HOST: redis-db
      APP_PERCENTAGE_HOSTNAME: http://app-percentage:8090
      DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/tenpo
      DATASOURCE_USERNAME: root
      DATASOURCE_PASS: tenpo
    profiles: ['DEV']
    ports:
      - '8080:8080'

volumes:
  db-postgres:



